import Foundation

// MARK: - UI localization helper

enum L {
    static func t(_ key: String) -> String {
        Strings.table[key]?[AppSettings.shared.language]
            ?? Strings.table[key]?[.en]
            ?? key
    }
}

// swiftlint:disable type_body_length
enum Strings {
    static let table: [String: [AppLanguage: String]] = [
        // common
        "common.ok": [.en: "OK", .ru: "ОК"],
        "common.cancel": [.en: "Cancel", .ru: "Отмена"],
        "common.continue": [.en: "Keep exploring", .ru: "Продолжить странствия"],
        "common.close": [.en: "Close", .ru: "Закрыть"],
        "common.back": [.en: "Back", .ru: "Назад"],
        "common.level": [.en: "Level", .ru: "Уровень"],
        "common.locked": [.en: "Locked", .ru: "Закрыто"],
        "common.gold": [.en: "Gold", .ru: "Золото"],
        "common.damage": [.en: "Damage", .ru: "Урон"],
        "common.defense": [.en: "Defense", .ru: "Защита"],
        "common.health": [.en: "Health", .ru: "Здоровье"],
        "common.mana": [.en: "Mana", .ru: "Мана"],
        "common.on": [.en: "On", .ru: "Вкл"],
        "common.off": [.en: "Off", .ru: "Выкл"],
        "common.yes": [.en: "Yes", .ru: "Да"],
        "common.no": [.en: "No", .ru: "Нет"],
        "common.empty": [.en: "Empty", .ru: "Пусто"],
        "common.points": [.en: "points", .ru: "очков"],
        "common.rank": [.en: "Rank", .ru: "Ранг"],
        "common.maxed": [.en: "MAX", .ru: "МАКС"],
        "common.reward": [.en: "Reward", .ru: "Награда"],
        "common.rewards": [.en: "Rewards", .ru: "Награды"],
        "common.price": [.en: "Price", .ru: "Цена"],
        // menu
        "menu.subtitle": [.en: "Echoes of the Fallen", .ru: "Эхо павших"],
        "menu.new": [.en: "New Game", .ru: "Новая игра"],
        "menu.continue": [.en: "Continue", .ru: "Продолжить"],
        "menu.slots": [.en: "Adventures", .ru: "Приключения"],
        "menu.howto": [.en: "How to Play", .ru: "Как играть"],
        "menu.ach": [.en: "Achievements", .ru: "Достижения"],
        "menu.settings": [.en: "Settings", .ru: "Настройки"],
        "menu.tap": [.en: "Tap to start", .ru: "Нажми, чтобы начать"],
        // slots
        "slots.title": [.en: "Choose Adventure", .ru: "Выбор приключения"],
        "slots.empty": [.en: "Empty slot", .ru: "Пустой слот"],
        "slots.delete": [.en: "Delete", .ru: "Удалить"],
        "slots.deleteTitle": [.en: "Delete adventure?", .ru: "Удалить приключение?"],
        "slots.deleteMsg": [.en: "All progress in this slot will be lost.", .ru: "Весь прогресс в этом слоте будет потерян."],
        "slots.lastPlayed": [.en: "Played", .ru: "Играли"],
        // character
        "char.title": [.en: "Create Hero", .ru: "Создание героя"],
        "char.name": [.en: "Name", .ru: "Имя"],
        "char.namePh": [.en: "Enter hero name", .ru: "Введи имя героя"],
        "char.random": [.en: "Random", .ru: "Случайно"],
        "char.class": [.en: "Class", .ru: "Класс"],
        "char.start": [.en: "Begin Adventure", .ru: "Начать приключение"],
        "char.str": [.en: "STR", .ru: "СИЛ"],
        "char.agi": [.en: "AGI", .ru: "ЛВК"],
        "char.vit": [.en: "VIT", .ru: "ВЫН"],
        "char.int": [.en: "INT", .ru: "ИНТ"],
        "char.weapon": [.en: "Starting weapon", .ru: "Стартовое оружие"],
        "char.bonus": [.en: "Bonus skill", .ru: "Бонусный навык"],
        // hud
        "hud.interact": [.en: "Interact", .ru: "Действие"],
        "hud.talk": [.en: "Talk", .ru: "Говорить"],
        "hud.open": [.en: "Open", .ru: "Открыть"],
        "hud.enter": [.en: "Enter", .ru: "Войти"],
        "hud.read": [.en: "Read", .ru: "Прочитать"],
        "hud.sealed": [.en: "Sealed: defeat the guardian!", .ru: "Запечатано: победи стража!"],
        "hud.combo": [.en: "Combo", .ru: "Серия"],
        "hud.questNew": [.en: "New quest", .ru: "Новый квест"],
        "hud.questDone": [.en: "Quest complete", .ru: "Квест выполнен"],
        "hud.levelUp": [.en: "Level up!", .ru: "Новый уровень!"],
        "hud.checkpoint": [.en: "Checkpoint", .ru: "Контрольная точка"],
        "hud.saved": [.en: "Game saved", .ru: "Игра сохранена"],
        "hud.bossDown": [.en: "Boss defeated!", .ru: "Босс повержен!"],
        "hud.noMana": [.en: "Not enough mana", .ru: "Не хватает маны"],
        "hud.noPotions": [.en: "No potions left", .ru: "Зелий не осталось"],
        // inventory
        "inv.title": [.en: "Inventory", .ru: "Инвентарь"],
        "inv.equipment": [.en: "Equipment", .ru: "Снаряжение"],
        "inv.bag": [.en: "Backpack", .ru: "Рюкзак"],
        "inv.weapon": [.en: "Weapon", .ru: "Оружие"],
        "inv.armor": [.en: "Armor", .ru: "Броня"],
        "inv.trinket": [.en: "Trinket", .ru: "Амулет"],
        "inv.equip": [.en: "Equip", .ru: "Надеть"],
        "inv.equipped": [.en: "Equipped", .ru: "Надето"],
        "inv.unequip": [.en: "Take off", .ru: "Снять"],
        "inv.use": [.en: "Use", .ru: "Использовать"],
        "inv.drop": [.en: "Drop", .ru: "Выбросить"],
        "inv.all": [.en: "All", .ru: "Все"],
        "inv.consumable": [.en: "Usable", .ru: "Расходуемые"],
        "inv.material": [.en: "Materials", .ru: "Материалы"],
        "inv.keyItem": [.en: "Key items", .ru: "Ключевые"],
        "inv.effect": [.en: "Effect", .ru: "Эффект"],
        "inv.sell": [.en: "Sell value", .ru: "Цена продажи"],
        "inv.heal": [.en: "Restores", .ru: "Восстанавливает"],
        "inv.hp": [.en: "HP", .ru: "ОЗ"],
        "inv.mp": [.en: "MP", .ru: "ОМ"],
        // skills
        "skill.title": [.en: "Growth", .ru: "Развитие"],
        "skill.tabs.skills": [.en: "Skills", .ru: "Навыки"],
        "skill.tabs.attrs": [.en: "Attributes", .ru: "Атрибуты"],
        "skill.points": [.en: "Skill points", .ru: "Очки навыков"],
        "skill.attrPoints": [.en: "Attribute points", .ru: "Очки атрибутов"],
        "skill.learn": [.en: "Learn", .ru: "Изучить"],
        "skill.improve": [.en: "Improve", .ru: "Улучшить"],
        "skill.req": [.en: "Requires", .ru: "Требует"],
        "skill.summary": [.en: "Current power", .ru: "Текущая мощь"],
        "skill.str.d": [.en: "+melee damage, +carry of heavy blows", .ru: "+урон в ближнем бою"],
        "skill.agi.d": [.en: "+speed, +crit chance", .ru: "+скорость, +шанс крита"],
        "skill.vit.d": [.en: "+max health", .ru: "+максимум здоровья"],
        "skill.int.d": [.en: "+max mana, +spell power", .ru: "+максимум маны, +сила заклинаний"],
        // quests
        "quest.title": [.en: "Journal", .ru: "Журнал"],
        "quest.main": [.en: "Main", .ru: "Сюжет"],
        "quest.side": [.en: "Side", .ru: "Второстепенные"],
        "quest.done": [.en: "Completed", .ru: "Завершённые"],
        "quest.objectives": [.en: "Objectives", .ru: "Цели"],
        "quest.track": [.en: "Track", .ru: "Отслеживать"],
        "quest.tracked": [.en: "Tracked", .ru: "Отслеживается"],
        "quest.turnIn": [.en: "Return to", .ru: "Вернись к"],
        "quest.giver": [.en: "Quest giver", .ru: "Квестодатель"],
        "quest.ready": [.en: "Ready to turn in!", .ru: "Можно сдавать!"],
        // dialogue
        "dlg.leave": [.en: "Farewell", .ru: "Прощай"],
        "dlg.shop": [.en: "Trade", .ru: "Торговля"],
        "dlg.heal": [.en: "Rest & heal (free)", .ru: "Отдохнуть и вылечиться"],
        "dlg.healed": [.en: "You feel refreshed!", .ru: "Ты чувствуешь прилив сил!"],
        // shop
        "shop.title": [.en: "Merchant", .ru: "Торговец"],
        "shop.buy": [.en: "Buy", .ru: "Купить"],
        "shop.poor": [.en: "Not enough gold", .ru: "Не хватает золота"],
        "shop.bought": [.en: "Purchased", .ru: "Куплено"],
        // pause
        "pause.title": [.en: "Paused", .ru: "Пауза"],
        "pause.resume": [.en: "Resume", .ru: "Продолжить"],
        "pause.save": [.en: "Save game", .ru: "Сохранить"],
        "pause.settings": [.en: "Settings", .ru: "Настройки"],
        "pause.journal": [.en: "Journal", .ru: "Журнал"],
        "pause.quit": [.en: "Save & exit", .ru: "Сохранить и выйти"],
        // settings
        "set.title": [.en: "Settings", .ru: "Настройки"],
        "set.language": [.en: "Language", .ru: "Язык"],
        "set.difficulty": [.en: "Difficulty", .ru: "Сложность"],
        "set.easy": [.en: "Story", .ru: "История"],
        "set.normal": [.en: "Adventure", .ru: "Приключение"],
        "set.hard": [.en: "Nightmare", .ru: "Кошмар"],
        "set.easy.d": [.en: "Relaxed: weaker enemies, gentle death penalty.", .ru: "Спокойно: слабые враги, мягкий штраф за смерть."],
        "set.normal.d": [.en: "Balanced challenge.", .ru: "Сбалансированная сложность."],
        "set.hard.d": [.en: "Brutal enemies, harsh death penalty.", .ru: "Жестокие враги, суровый штраф за смерть."],
        "set.master": [.en: "Master volume", .ru: "Общая громкость"],
        "set.music": [.en: "Music", .ru: "Музыка"],
        "set.sfx": [.en: "Sound effects", .ru: "Звуковые эффекты"],
        "set.haptics": [.en: "Haptics", .ru: "Вибрация"],
        "set.minimap": [.en: "Minimap", .ru: "Миникарта"],
        "set.effects": [.en: "Rich effects", .ru: "Богатые эффекты"],
        "set.graphics": [.en: "Graphics", .ru: "Графика"],
        "set.quality.auto": [.en: "Auto", .ru: "Авто"],
        "set.quality.high": [.en: "High", .ru: "Высокая"],
        "set.quality.medium": [.en: "Medium", .ru: "Средняя"],
        "set.quality.low": [.en: "Low", .ru: "Низкая"],
        "set.device": [.en: "Device", .ru: "Устройство"],
        "hud.fullHp": [.en: "Health is already full", .ru: "Здоровье уже полное"],
        "set.credits": [.en: "A dark fairy-tale action RPG. Made with SpriteKit & SwiftUI.", .ru: "Тёмная сказочная action-RPG. Сделана на SpriteKit и SwiftUI."],
        // death / victory
        "death.title": [.en: "You Died", .ru: "Ты погиб"],
        "death.sub": [.en: "Darkness takes its toll...", .ru: "Тьма берёт свою дань..."],
        "death.respawn": [.en: "Revive at checkpoint", .ru: "Возродиться"],
        "death.lost": [.en: "Gold lost", .ru: "Потеряно золота"],
        "death.menu": [.en: "Abandon run", .ru: "Выйти"],
        "victory.title": [.en: "Dawn Breaks!", .ru: "Рассвет настал!"],
        "victory.sub": [.en: "The last echo fades. Aetheria is free.", .ru: "Последнее эхо затихает. Этерия свободна."],
        "victory.stats": [.en: "Adventure statistics", .ru: "Статистика приключения"],
        "victory.kills": [.en: "Enemies slain", .ru: "Врагов повержено"],
        "victory.time": [.en: "Play time", .ru: "Время игры"],
        "victory.quests": [.en: "Quests completed", .ru: "Квестов завершено"],
        "victory.chests": [.en: "Chests opened", .ru: "Сундуков открыто"],
        "victory.bosses": [.en: "Bosses defeated", .ru: "Боссов повержено"],
        "victory.menu": [.en: "Return to menu", .ru: "В меню"],
        // how to
        "howto.title": [.en: "How to Play", .ru: "Как играть"],
        "howto.move": [.en: "Left stick / A,D — move. Up / W — climb ladders.", .ru: "Левый стик / A,D — движение. Вверх / W — лезть по лестницам."],
        "howto.jump": [.en: "Jump button / Space — jump, twice for double jump (skill).", .ru: "Кнопка прыжка / Пробел — прыжок, дважды — двойной прыжок (навык)."],
        "howto.attack": [.en: "Sword / J — 3-hit combo. Bolt / K — magic bolt for mana.", .ru: "Меч / J — комбо из 3 ударов. Снаряд / K — магический болт за ману."],
        "howto.dash": [.en: "Dash / Shift — dodge roll with brief invulnerability.", .ru: "Рывок / Shift — кувырок с краткой неуязвимостью."],
        "howto.interact": [.en: "Hand / E — talk, open chests, read signs, enter portals.", .ru: "Рука / E — говорить, открывать сундуки, читать знаки, входить в порталы."],
        "howto.goal": [.en: "Follow the main quest, defeat 3 guardians and close the Rift.", .ru: "Следуй сюжету, победи 3 стражей и закрой Разлом."],
        "howto.potion": [.en: "Potion button / Q — drink a healing potion.", .ru: "Кнопка зелья / Q — выпить лечебное зелье."],
        // achievements
        "ach.title": [.en: "Achievements", .ru: "Достижения"],
        "ach.locked": [.en: "Locked", .ru: "Закрыто"],
        "ach.got": [.en: "Achievement unlocked!", .ru: "Достижение получено!"],
        // toasts
        "toast.item": [.en: "Received", .ru: "Получено"],
        "toast.gold": [.en: "Gold", .ru: "Золото"],
        "toast.skill": [.en: "Skill learned", .ru: "Навык изучен"],
        // level names fallback
        "level.complete": [.en: "Region cleared!", .ru: "Регион зачищен!"],
    ]
}
